// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package {{ds.package_name}};
    {{hwif.get_package_contents()|indent}}
endpackage
